# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-03 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetv',
            name='inventory',
            field=models.IntegerField(default=100, verbose_name='库存'),
        ),
        migrations.AddField(
            model_name='perfermodel',
            name='inventory',
            field=models.IntegerField(default=100, verbose_name='库存'),
        ),
        migrations.AddField(
            model_name='tvhot',
            name='inventory',
            field=models.IntegerField(default=100, verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='perfermodel',
            name='discount',
            field=models.CharField(default='', max_length=100, verbose_name='折扣'),
        ),
        migrations.AlterField(
            model_name='tvhot',
            name='discount',
            field=models.CharField(default='', max_length=100, verbose_name='折扣'),
        ),
    ]
