# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-03 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20191003_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetv',
            name='sales',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
        migrations.AddField(
            model_name='perfermodel',
            name='sales',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
        migrations.AddField(
            model_name='tvhot',
            name='sales',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
    ]
