# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-03 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_shopnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField(verbose_name='商品分类id')),
                ('typename', models.CharField(max_length=100, verbose_name='商品分类名称')),
                ('childtypename', models.CharField(max_length=500, verbose_name='子分类的名称')),
                ('childtypeid', models.IntegerField(verbose_name='子分类的id')),
                ('brand', models.CharField(max_length=500, verbose_name='推荐品牌')),
                ('activityid', models.IntegerField(verbose_name='热门活动id')),
            ],
            options={
                'db_table': 'myshop_goodstype',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsid', models.IntegerField(verbose_name='商品id')),
                ('img', models.CharField(max_length=100, verbose_name='商品图片')),
                ('name', models.CharField(max_length=200, verbose_name='商品短名称')),
                ('specifics', models.CharField(max_length=100, verbose_name='商品规格')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='售价')),
                ('marketprice', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='市场价')),
                ('categoryid', models.IntegerField(verbose_name='所属分类id')),
                ('childcid', models.IntegerField(verbose_name='所属子分类id')),
                ('childcidname', models.CharField(max_length=100, verbose_name='自分类名称')),
                ('inventory', models.IntegerField(verbose_name='库存')),
                ('sales', models.IntegerField(verbose_name='销量')),
            ],
            options={
                'db_table': 'myshop_goods',
            },
        ),
        migrations.CreateModel(
            name='HotActivitys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityid', models.IntegerField(verbose_name='热门活动id')),
                ('img', models.CharField(max_length=150, verbose_name='活动图片信息')),
                ('links', models.CharField(max_length=150, verbose_name='活动路径')),
            ],
            options={
                'db_table': 'myshop_activities',
            },
        ),
    ]
