# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-03 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_foodtype_goods_hotactivitys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='marketprice',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='specifics',
        ),
        migrations.AddField(
            model_name='goods',
            name='discount',
            field=models.CharField(max_length=50, null=True, verbose_name='优惠'),
        ),
    ]
