# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-04 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_auto_20191003_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfermodel',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='tvhot',
            name='discount',
        ),
        migrations.AddField(
            model_name='perfermodel',
            name='goodsid',
            field=models.IntegerField(default=0, verbose_name='商品id'),
        ),
        migrations.AddField(
            model_name='tvhot',
            name='goodsid',
            field=models.IntegerField(default=0, verbose_name='商品id'),
        ),
    ]
