# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-05 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_auto_20191004_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='discount',
        ),
        migrations.AddField(
            model_name='goods',
            name='comments',
            field=models.IntegerField(default=100, verbose_name='评论'),
        ),
        migrations.AddField(
            model_name='goods',
            name='introduce',
            field=models.CharField(default='', max_length=500, verbose_name='商品介绍'),
        ),
    ]
