# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-05 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_auto_20191005_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='introduce',
            field=models.CharField(default='', max_length=1000, verbose_name='商品介绍'),
        ),
    ]
