# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-05 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_auto_20191005_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='frombrand',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='所属品牌'),
        ),
    ]
