# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-06 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_goods_frombrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfermodel',
            name='comments',
            field=models.IntegerField(default=100, verbose_name='评论'),
        ),
        migrations.AddField(
            model_name='perfermodel',
            name='frombrand',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='所属品牌'),
        ),
        migrations.AddField(
            model_name='perfermodel',
            name='introduce',
            field=models.CharField(default='', max_length=1000, verbose_name='商品介绍'),
        ),
        migrations.AddField(
            model_name='tvhot',
            name='comments',
            field=models.IntegerField(default=100, verbose_name='评论'),
        ),
        migrations.AddField(
            model_name='tvhot',
            name='frombrand',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='所属品牌'),
        ),
        migrations.AddField(
            model_name='tvhot',
            name='introduce',
            field=models.CharField(default='', max_length=1000, verbose_name='商品介绍'),
        ),
    ]
