# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-10 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0011_auto_20191006_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='titlepage',
            field=models.CharField(default='', max_length=100, verbose_name='封面图片'),
        ),
    ]
