# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-09 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=100, verbose_name='总订单编号')),
                ('goods_id', models.IntegerField(verbose_name='商品id')),
                ('counts', models.IntegerField(verbose_name='商品数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='商品单价')),
                ('note', models.CharField(max_length=200, verbose_name='备注信息')),
            ],
            options={
                'db_table': 'myshop_order_detail',
            },
        ),
        migrations.RenameField(
            model_name='order',
            old_name='uid',
            new_name='userid',
        ),
    ]
