# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-09 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191009_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='note',
            field=models.CharField(default='无', max_length=200, null=True, verbose_name='备注信息'),
        ),
    ]
