# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-09 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191009_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='商品单价'),
        ),
    ]
