# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-09 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191009_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='note',
        ),
    ]
