# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-08 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191005_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='', max_length=11, verbose_name='用户名'),
        ),
    ]
